name: Neon
version: 1.1.0-1.alpha8
author: jdcraft
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8]
load: POSTWORLD
main: jdcraft\neon\Main
permissions:
 neon:
  description: all permissions for neon
commands:
 neon:
  description: Neon Commands