name: Neon
version: "1.0.8"
author: jdcraft
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: POSTWORLD
main: jdcraft\neon\Main
permissions:
 neon:
  description: all permissions for neon
commands:
 neon:
  description: Neon Commands