name: Neon
version: "1.0.5"
author: jdcraft
api: [2.0.0, 3.0.0-ALPHA1]
load: POSTWORLD
main: jdcraft\neon\Main
permissions:
 neon:
  description: all permissions for neon
commands:
 neon:
  description: Neon Commands