name: Neon
version: 1.1.0-2
author: jdcraft
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
main: jdcraft\neon\Main
permissions:
 neon:
  description: all permissions for neon
commands:
 neon:
  description: Neon Commands